server:
  port: 8080

project:
  database:
    api: http://localhost:8090/db/api/v1


spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /*
  data:
    redis:
      port: 6379
      host: localhost

  kafka:
    producer:
      acks: all
      retries: 3
    bootstrap-servers: localhost:9092
    topic:
      notification: NOTIFICATION_TOPIC
    group-id:
      from-node: FROM_NODE_GROUP_ID
